package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Kotlinproject_HttpsGithubComAnasthanKotlinprojectGitRefsHeadsMain'
in the project with id = 'Kotlinproject', and delete the patch script.
*/
create(RelativeId("Kotlinproject"), GitVcsRoot({
    id("Kotlinproject_HttpsGithubComAnasthanKotlinprojectGitRefsHeadsMain")
    name = "https://github.com/anasthan/kotlinproject.git#refs/heads/main"
    url = "https://github.com/anasthan/kotlinproject.git"
    branch = "refs/heads/main"
    branchSpec = "refs/heads/*"
    authMethod = password {
        userName = "ankit.asthana49@hotmail.com"
        password = "credentialsJSON:7cbaf38c-f013-4a17-b458-ea8f11c94694"
    }
}))

